/* ─────────────────────────────────────────────────────────────
   StormCloud — generated by Bolt Bench

   Four of the five files here are regenerated wholesale every time you
   export from the bench: layout.h, tuning.h, storm.h and this one.
   config.h is yours and is never overwritten — pins, logging and
   palettes live there.
   ───────────────────────────────────────────────────────────── */
#include "storm.h"
#include "controls.h"

void setup() {
#if STORM_LOG
  Serial.begin(STORM_LOG_BAUD);
  uint32_t waited = millis();                 // USB CDC needs a moment to enumerate,
  while (!Serial && millis() - waited < 1500) { }   // but never hang without a host
#endif
  FastLED.addLeds<LED_TYPE, LED_PIN, COLOR_ORDER>(leds, NUM_LEDS).setCorrection(TypicalLEDStrip);
  g_bright = scale8(MASTER, TRIM);
  FastLED.setBrightness(g_bright);
  updatePalette();
  // 300 px at full white is ~18 A at 5 V and this animation really does flash
  // most of the cloud at once. Uncomment to let FastLED hold the peak down:
  // FastLED.setMaxPowerInVoltsAndMilliamps(5, 4000);
  random16_set_seed(0x1337);            // same seed the bench previewed
  for (uint8_t i = 0; i < MAX_STRIKES; i++) strikes[i].active = false;
  logBoot();
  controlsBegin();
}

void loop() {
  controlsUpdate(false);
  uint32_t now = stormClock();     // virtual: the speed knob stretches this
  frameNo++;
  fill_solid(leds, NUM_LEDS, CRGB::Black);
  renderAmbient(now);

  if (now >= nextStrikeAt) {
    uint8_t seg = randomBolt();
    trigger(seg, now);
    if (random8() < DBL_CHANCE) trigger(randomBolt(), now + rndR(40, CLUSTER_MS + 1));
    nextStrikeAt = now + rndR(GAP_MIN, GAP_MAX + 1);
  }

  for (uint8_t i = 0; i < MAX_STRIKES; i++) renderStrike(strikes[i], now);

  logDashboard(millis());     // wall-clock, not the speed-scaled storm clock

  FastLED.show();
}
