/* Storm engine, generated by Bolt Bench — overwritten on export. */
#pragma once
#include <FastLED.h>
#include "config.h"
#include "layout.h"
#include "tuning.h"

CRGB leds[NUM_LEDS];

/* ── palette ────────────────────────────────────────────────── */
/* Both endpoints of the heat ramp, resolved once per frame rather than
   per pixel, so addLed() stays three mix8 and three scale8. */
CRGB coolC, hotC;

void updatePalette() {
  hsv2rgb_rainbow(CHSV(HUE, SAT,     255), coolC);
  hsv2rgb_rainbow(CHSV(HUE, HOT_SAT, 255), hotC);
  LOG("[storm] palette hue=%u sat=%u hotSat=%u -> cool #%02X%02X%02X hot #%02X%02X%02X\n",
      (unsigned)HUE, (unsigned)SAT, (unsigned)HOT_SAT,
      coolC.r, coolC.g, coolC.b, hotC.r, hotC.g, hotC.b);
}

/* ── helpers ────────────────────────────────────────────────── */
static inline uint8_t mix8(uint8_t a, uint8_t b, uint8_t amt) {
  return a + (uint8_t)(((int16_t)(b - a) * (int16_t)amt) >> 8);
}
static inline uint8_t dist8(int16_t dx, int16_t dy) {
  uint16_t ax = dx < 0 ? -dx : dx, ay = dy < 0 ? -dy : dy;
  uint16_t hi = ax > ay ? ax : ay, lo = ax > ay ? ay : ax;
  uint16_t d = hi + ((lo * 85) >> 8);
  return d > 255 ? 255 : (uint8_t)d;
}
// stateless per-pixel noise: the same pixel flickers the same way each frame
static inline uint8_t hash8(uint16_t a, uint16_t b) {
  uint32_t h = ((uint32_t)a * 73856093UL) ^ ((uint32_t)b * 19349663UL);
  h ^= h >> 13;
  return (uint8_t)((h * 2654435761UL) >> 24);
}
static inline uint16_t rndR(uint16_t lo, uint16_t hi) {
  return hi <= lo ? lo : lo + random16(hi - lo);
}

/* ── strike model ───────────────────────────────────────────── */
struct Stroke { uint16_t at; uint16_t dur; uint8_t b; uint8_t upTo; };
struct Strike {
  bool     active;
  uint8_t  seg;
  uint32_t t0;
  uint16_t leaderMs;
  uint8_t  nStrokes;
  Stroke   strokes[MAX_STROKES];
  uint16_t lastEnd;
  uint16_t glowMs;
  uint16_t total;
  uint8_t  ox, oy;
  uint8_t  forkMask;    // bit k set = restrike k travels into the forks
  uint8_t  rumbleSeed;
};
Strike strikes[MAX_STRIKES];
uint32_t nextStrikeAt = 700;
uint16_t frameNo = 0;

void makeStrike(uint8_t slot, uint8_t segIdx, uint32_t t0) {
  Strike &s = strikes[slot];
  Segment seg; memcpy_P(&seg, &SEGMENTS[segIdx], sizeof(Segment));
  s.active = true; s.seg = segIdx; s.t0 = t0;
  s.leaderMs = rndR(LEAD_MIN, LEAD_MAX + 1);
  s.nStrokes = rndR(STRK_MIN, STRK_MAX + 1);
  if (s.nStrokes > MAX_STROKES) s.nStrokes = MAX_STROKES;
  uint16_t t = s.leaderMs;
  for (uint8_t k = 0; k < s.nStrokes; k++) {
    uint16_t dur = rndR(DUR_MIN, DUR_MAX + 1);
    bool partial = (k > 0) && (random8() < PARTIAL);
    s.strokes[k].at   = t;
    s.strokes[k].dur  = dur;
    s.strokes[k].b    = (k == 0) ? 255 : (uint8_t)rndR(110, 256);
    s.strokes[k].upTo = partial ? (uint8_t)rndR(90, 210) : 255;
    t += dur + rndR(RGAP_MIN, RGAP_MAX + 1);
  }
  s.lastEnd = s.strokes[s.nStrokes - 1].at + s.strokes[s.nStrokes - 1].dur;
  uint16_t g = GLOW_MS + rndR(0, 200); g = (g > 80) ? g - 80 : 40;
  s.glowMs = g;
  s.total  = s.lastEnd + (s.glowMs > CLOUD_MS ? s.glowMs : CLOUD_MS);
  s.forkMask = 1;                       // the return stroke always forks
  for (uint8_t k = 1; k < s.nStrokes; k++)
    if (random8() < FORK_FOLLOW) s.forkMask |= (1 << k);
  s.ox = seg.ox; s.oy = seg.oy;
  s.rumbleSeed = random8();
}

int8_t freeSlot() {
  for (uint8_t i = 0; i < MAX_STRIKES; i++) if (!strikes[i].active) return i;
  return -1;
}
void trigger(uint8_t segIdx, uint32_t at) {
  int8_t slot = freeSlot();
  if (slot < 0) {
#if STORM_LOG
    Segment sg; memcpy_P(&sg, &SEGMENTS[segIdx], sizeof(Segment));
    LOG("[storm] DROPPED %s — all %u strike slots busy\n", sg.name, (unsigned)MAX_STRIKES);
#endif
    return;
  }
  makeStrike(slot, segIdx, at);
#if STORM_LOG
  const Strike &s = strikes[slot];
  Segment sg; memcpy_P(&sg, &SEGMENTS[segIdx], sizeof(Segment));
  LOG("[storm] strike  %-16s slot=%u leader=%ums strokes=%u forkMask=0x%02X total=%ums\n",
      sg.name, (unsigned)slot, (unsigned)s.leaderMs, (unsigned)s.nStrokes,
      (unsigned)s.forkMask, (unsigned)s.total);
#endif
}

/* ── per-pixel accumulate ───────────────────────────────────── */
void addLed(uint16_t i, uint8_t bright, uint8_t heat, uint16_t pos, uint16_t len) {
  if (i >= NUM_LEDS || bright == 0) return;
  if (len > 1 && TAPER) {
    uint8_t t = (uint8_t)((uint32_t)pos * 255 / len);
    bright = qsub8(bright, scale8(bright, scale8(t, TAPER)));
    if (!bright) return;
  }
  leds[i].r = qadd8(leds[i].r, scale8(mix8(coolC.r, hotC.r, heat), bright));
  leds[i].g = qadd8(leds[i].g, scale8(mix8(coolC.g, hotC.g, heat), bright));
  leds[i].b = qadd8(leds[i].b, scale8(mix8(coolC.b, hotC.b, heat), bright));
}

/* ── channel envelope: intensity + heat (white ↔ blue) ──────── */
void envelope(const Strike &s, uint16_t e, uint8_t &env, uint8_t &heat, uint8_t &upTo, int8_t &idx) {
  env = 0; heat = 0; upTo = 255; idx = -1;
  for (uint8_t k = 0; k < s.nStrokes; k++) {
    const Stroke &st = s.strokes[k];
    if (e >= st.at && e < (uint16_t)(st.at + st.dur)) {
      uint8_t p = (uint8_t)((uint32_t)(e - st.at) * 255 / st.dur);
      uint8_t v = scale8(st.b, qsub8(255, scale8(p, 150)));
      if (v > env) { env = v; heat = 255; upTo = st.upTo; idx = (int8_t)k; }
    }
  }
  if (e > s.lastEnd) {
    uint32_t q = (uint32_t)(e - s.lastEnd) * 255 / s.glowMs;
    uint8_t p = q > 255 ? 255 : (uint8_t)q;
    uint8_t inv = qsub8(255, p);
    uint8_t fall = scale8(scale8(inv, inv), 150);
    if (fall > env) { env = fall; heat = inv; upTo = 255; idx = -1; }  // afterglow: all channels
  }
}

/* One channel of the strike tree.

   A fork's leader starts when the parent's leader head reaches the attachment
   point, and travels at the same propagation velocity (same pixels per ms), so
   a branch and its trunk arrive at about the same moment — which is what real
   forked lightning does. Depth is capped at 3. */
void renderChannel(const Strike &s, uint16_t e, uint8_t segIdx,
                   uint16_t leaderStart, uint16_t leaderDur, uint8_t dim, uint8_t depth,
                   uint8_t env, uint8_t heat, uint8_t upTo, int8_t sidx) {
  if (depth > 3) return;
  Segment seg; memcpy_P(&seg, &SEGMENTS[segIdx], sizeof(Segment));
  uint16_t start = seg.start, len = seg.len;
  if (len < 1) return;

  if (e >= leaderStart && (uint16_t)(e - leaderStart) < leaderDur) {   // stepped leader
    uint16_t le = e - leaderStart;
    uint16_t head = (uint16_t)(((uint32_t)le * len) / leaderDur);
    for (uint16_t i = 0; i <= head && i < len; i++) {
      uint8_t b = qsub8(240, (uint8_t)((head - i) * TRAIL));
      if (b) addLed(start + i, scale8(b, dim), 200, i, len);
    }
  }

  bool partake = (depth == 0) || (sidx < 0) || ((s.forkMask >> sidx) & 1);
  if (env && partake) {                                   // return + restrikes
    uint16_t lim = (uint16_t)(((uint32_t)len * upTo) >> 8) + 1;
    if (lim > len) lim = len;
    for (uint16_t i = 0; i < lim; i++) {
      uint8_t flick = qsub8(255, hash8(start + i, frameNo >> 1) >> 3);
      addLed(start + i, scale8(scale8(env, flick), dim), heat, i, len);
    }
  }

  for (uint8_t c = 0; c < NUM_SEGMENTS; c++) {            // recurse into forks
    Segment ch; memcpy_P(&ch, &SEGMENTS[c], sizeof(Segment));
    if (ch.parent != (int8_t)segIdx || ch.len < 1) continue;
    uint16_t cStart = leaderStart + (uint16_t)(((uint32_t)leaderDur * ch.forkAt) >> 8);
    uint16_t cDur = (uint16_t)(((uint32_t)leaderDur * ch.len) / len);
    if (cDur < 4) cDur = 4;
    renderChannel(s, e, c, cStart, cDur, scale8(dim, FORK_DIM), depth + 1, env, heat, upTo, sidx);
  }
}

void renderStrike(Strike &s, uint32_t now) {
  if (!s.active) return;
  if (now < s.t0) return;
  uint32_t el = now - s.t0;
  if (el > s.total) {
    s.active = false;
#if STORM_LOG
    Segment sg; memcpy_P(&sg, &SEGMENTS[s.seg], sizeof(Segment));
    LOG("[storm]   done  %-16s after %ums\n", sg.name, (unsigned)el);
#endif
    return;
  }
  uint16_t e = (uint16_t)el;

  Segment seg; memcpy_P(&seg, &SEGMENTS[s.seg], sizeof(Segment));
  if (seg.len < 1) return;

  uint8_t env, heat, upTo; int8_t sidx;
  envelope(s, e, env, heat, upTo, sidx);
  renderChannel(s, e, s.seg, 0, s.leaderMs, 255, 0, env, heat, upTo, sidx);

  // the cloud lights in sympathy, by distance from the channel root
  uint8_t glowP = 0;
  if (e > s.lastEnd) {
    uint32_t q = (uint32_t)(e - s.lastEnd) * 255 / CLOUD_MS;
    glowP = q > 255 ? 255 : (uint8_t)q;
  }
  uint8_t cenv = env;
  if (glowP) {
    uint8_t inv = qsub8(255, glowP);
    uint8_t fall = scale8(inv, inv);
    if (fall > cenv) cenv = fall;
  }
  cenv = scale8(cenv, CLOUD_FLASH);
  if (cenv > 1) {
    uint8_t rum = RUMBLE ? scale8(RUMBLE, sin8((uint8_t)((now * 3) >> 4) + s.rumbleSeed)) : 0;
    uint8_t cheat = qsub8(heat, scale8(glowP, 200));
    for (uint8_t g = 0; g < NUM_SEGMENTS; g++) {
      Segment cs; memcpy_P(&cs, &SEGMENTS[g], sizeof(Segment));
      if (cs.isBolt) continue;
      for (uint16_t j = cs.start; j < cs.start + cs.len; j++) {
        int16_t dx = (int16_t)pgm_read_byte(&LED_X[j]) - (int16_t)s.ox;
        int16_t dy = (int16_t)pgm_read_byte(&LED_Y[j]) - (int16_t)s.oy;
        uint8_t atten = qsub8(255, scale8(dist8(dx, dy), CLOUD_SPREAD));
        if (!atten) continue;
        uint8_t v = scale8(cenv, atten);
        if (rum) v = qsub8(v, scale8(v, scale8(rum, hash8(j, s.rumbleSeed))));
        if (v) addLed(j, v, cheat, 0, 1);
      }
    }
  }
}

void renderAmbient(uint32_t now) {
  if (!AMB_LEVEL) return;
  uint8_t t1 = (uint8_t)((now * AMB_SPEED) / 64);
  uint8_t t2 = (uint8_t)((now * AMB_SPEED) / 160);
  for (uint8_t g = 0; g < NUM_SEGMENTS; g++) {
    Segment cs; memcpy_P(&cs, &SEGMENTS[g], sizeof(Segment));
    if (cs.isBolt) continue;
    for (uint16_t j = cs.start; j < cs.start + cs.len; j++) {
      uint8_t a = sin8(t1 + (uint8_t)(j * 5));
      uint8_t b = sin8(t2 - (uint8_t)(j * 11) + 64);
      uint8_t v = scale8(scale8(a, b), AMB_LEVEL);
      if (v) addLed(j, v, 40, 0, 1);
    }
  }
}

/* ── main loop ──────────────────────────────────────────────── */
// forks are never struck directly — they light because their parent did
uint8_t randomBolt() {
  uint8_t bolts[NUM_SEGMENTS], n = 0;
  for (uint8_t i = 0; i < NUM_SEGMENTS; i++) {
    Segment sg; memcpy_P(&sg, &SEGMENTS[i], sizeof(Segment));
    if (sg.isBolt && sg.parent < 0) bolts[n++] = i;
  }
  return n ? bolts[random8() % n] : 0;
}

void logBoot() {
#if STORM_LOG
  LOG("\n[storm] StormCloud ready — %u px, %u segments, pin %u, master %u\n",
      (unsigned)NUM_LEDS, (unsigned)NUM_SEGMENTS, (unsigned)LED_PIN, (unsigned)MASTER);
  LOG("[storm] %-16s %5s %5s %6s  %s\n", "segment", "start", "len", "role", "attachment");
  for (uint8_t i = 0; i < NUM_SEGMENTS; i++) {
    Segment sg; memcpy_P(&sg, &SEGMENTS[i], sizeof(Segment));
    if (sg.parent < 0) {
      LOG("[storm] %-16s %5u %5u %6s  %s\n", sg.name, (unsigned)sg.start, (unsigned)sg.len,
          sg.isBolt ? "bolt" : "cloud", sg.isBolt ? "root channel" : "-");
    } else {
      Segment pa; memcpy_P(&pa, &SEGMENTS[sg.parent], sizeof(Segment));
      LOG("[storm] %-16s %5u %5u %6s  off %s at %u%%\n", sg.name, (unsigned)sg.start,
          (unsigned)sg.len, "fork", pa.name, (unsigned)(sg.forkAt * 100 / 255));
    }
  }
  LOG("[storm] frame buffer %u B, strike pool %u B, segment table %u B\n\n",
      (unsigned)sizeof(leds), (unsigned)sizeof(strikes), (unsigned)sizeof(SEGMENTS));
#endif
}
