/* Generated by Bolt Bench — overwritten on export. */
#pragma once

#define GAP_MIN       1400
#define GAP_MAX       5200
#define DBL_CHANCE    70
#define CLUSTER_MS    180
#define LEAD_MIN      120
#define LEAD_MAX      240
#define TRAIL         34
#define TAPER         70
#define STRK_MIN      1
#define STRK_MAX      1
#define DUR_MIN       60
#define DUR_MAX       150
#define RGAP_MIN      30
#define RGAP_MAX      140
#define PARTIAL       0
#define FORK_DIM      120
#define FORK_FOLLOW   40
#define GLOW_MS       700
#define AMB_LEVEL     52
#define AMB_SPEED     14
#define CLOUD_FLASH   255
#define CLOUD_SPREAD  230
#define CLOUD_MS      1300
#define RUMBLE        150
#define MASTER        170
/* Colour. The hue lives in the AFTERGLOW, not the strike: HOT_SAT keeps the
   return stroke near white so it still reads as hot, and the pixel cools
   toward the fully saturated HUE as it fades. Push HOT_SAT up and it stops
   looking like lightning and starts looking like a coloured tube.
   TRIM scales MASTER per palette — green sits where the eye is most
   sensitive, so it needs pulling back relative to blue.
   See PALETTES[] in config.h for starting points. */
#define HUE           160      // FastLED hue: 0 red, 64 yellow, 96 green, 160 blue, 192 purple
#define SAT            19      // carried over from the old TINT; ~200 for a storm blue you can see
#define HOT_HUE       160      // peak hue; equal to HUE means no shift along the heat ramp
#define HOT_SAT         0      // saturation at the white-hot peak; keep low
#define TRIM          255      // per-palette brightness trim applied to MASTER
